### ISSUE TITLE
Show suggestions even if value.length is equal to zero

### ISSUE THREAD

**Issue by jidan70** [baldwmic/react-input-tags#87]
Hi, is there a way to show the full suggestions list just by focusing on the input please?
Thanks in advance

**Comment by jidan70** [comment]
I found a way to do that. I find that you use a property called showSuggestions, but the property is not in the documentation.

```javascript
InputImplementation = (inputImp) => {
    const {value} = this.state;
    const onFocus = () => {
      this.setState({showSuggestions : true})
      inputImp.handleOnChange({target : {value}})
    }
    const onChange = e => {
      this.onChange(e)
      inputImp.handleOnChange(e)
    }
    const onBlur = () => {
      this.setState({showSuggestions : false})
      inputImp.handleOnBlur()
    }
    
    return <input type="text"
      value={value}
      onBlur={onBlur}
      onChange={onChange}
      onFocus={onFocus}
      placeholder="test"/>
  }
```


```javascript
  render () {
    const {tags, placeholder, className = ''} = this.props
    const {showSuggestions} = this.state

    return <InputTags
      showSuggestions={showSuggestions}
      tags={tags}
      suggestions={this.state.suggestions}
      handleUpdateSuggestions={this.handleUpdateSuggestions}
      handleInsert={this.handleInsert}
      handleRemove={this.handleRemove}
      TagImplementation={this.TagImplementation}
      InputTagsClassName="InputSelect"
      inputPlaceholder={placeholder}
      InputImplementation={this.InputImplementation}
      SuggestionListImplementation={this.SuggestionListImplementation}
      SuggestionListClassName={'input-select-suggestion-list'}/>
  }
```

**Comment by baldwmic** [comment]
@jidan70 The reason `showSuggestions` boolean is not documented as a part of the external API is because it's actually an internal state key to the component `InputTagsDefault`. 

https://github.com/baldwmic/react-input-tags/blob/0cf1704fb6c2041cf2f0c50893f664ea42422e8d/src/implementation/InputTagsDefault.jsx#L155

This means that the default implementation of `InputTags` manages whether suggestions should be shown internally. Of course, you can always override the default implementation by passing in your own implementation with the prop `InputTagsImplementation`.

The reason your solution works is because the default implementation of `InputTags` also passes any additional props it doesn't expect to the `SuggestionListContainer` which will show/hide the suggestions.

https://github.com/baldwmic/react-input-tags/blob/0cf1704fb6c2041cf2f0c50893f664ea42422e8d/src/implementation/InputTagsDefault.jsx#L378

In your case, you're overwriting the `showSuggestions` props already being passed from the internal state of the component. Your solution works 👍

**Comment by baldwmic** [comment]
Unfortunately, when I wrote this, I wasn't as experience in advanced React patterns, so I'm aware customizing this React component for your own uses is a bit of a clunky experience. In fact, I've got an issue open for it here: https://github.com/baldwmic/react-input-tags/issues/73

I noticed @jidan70 you're reimplementing the `InputImplementation` and what's not ideal is this is currently the only way to do that. Ideally, one could re-use a lot of the internal components here in this library, and configure them for your specific use cases without needing to write a lot of code.

It would be awesome if you could comment on that other issue to provide feedback on what you think a better way to customize some of these components would be. I've posted some of my thoughts there too.
